# Generated by Django 5.1.2 on 2024-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_user_id',
            field=models.CharField(blank=True, help_text='Instagram User ID', max_length=50, null=True),
        ),
    ]
